# Generated by Django 5.0.1 on 2024-03-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, null=True)),
                ('m_name', models.CharField(max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('aadhar', models.FileField(null=True, upload_to='pics/')),
                ('c_name', models.CharField(max_length=100, null=True)),
                ('c_register_no', models.CharField(max_length=100, null=True)),
                ('c_email', models.CharField(max_length=100, null=True)),
                ('c_mobile', models.CharField(max_length=100, null=True)),
                ('c_address', models.CharField(max_length=100, null=True)),
                ('c_incorporation', models.ImageField(null=True, upload_to='pics/')),
                ('p_card', models.ImageField(null=True, upload_to='pics/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('date', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
