# Generated by Django 5.0.1 on 2024-03-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('your_email', models.CharField(max_length=100, null=True)),
                ('company_name_help', models.CharField(max_length=100, null=True)),
                ('subject_help', models.CharField(max_length=100, null=True)),
                ('select_department', models.CharField(max_length=100, null=True)),
                ('your_massage', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
