# Generated by Django 5.0.1 on 2024-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0002_customerhelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_reg',
            name='profile_photo',
            field=models.FileField(null=True, upload_to='pics/'),
        ),
    ]
