# Generated by Django 5.0.2 on 2024-03-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0003_customer_reg_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_reg',
            name='confirm_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer_reg',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer_reg',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
