# Generated by Django 5.0.2 on 2024-03-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0004_customer_reg_confirm_password_customer_reg_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_reg',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='customer_reg',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer_reg',
            name='user_name',
        ),
    ]
