# Generated by Django 5.0.1 on 2024-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentapp', '0005_remove_customer_reg_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_reg',
            name='unique_id',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
