# Generated by Django 5.0.1 on 2024-02-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_Page',
            new_name='RegPage',
        ),
    ]
