# Generated by Django 5.0.1 on 2024-02-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_photosubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_registration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_registration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_register_no', models.CharField(max_length=100, null=True)),
                ('company_email', models.CharField(max_length=100, null=True)),
                ('company_mobile', models.CharField(max_length=100, null=True)),
                ('company_address', models.CharField(max_length=100, null=True)),
                ('company_incorporation', models.ImageField(null=True, upload_to='images/')),
                ('pan_card', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
