# Generated by Django 5.0.1 on 2024-02-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admin_registration1_admin_registration2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_registration1',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='admin_registration2',
            name='company_incorporation',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='admin_registration2',
            name='pan_card',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
