# Generated by Django 5.0.1 on 2024-02-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_admin_registration1_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Login',
        ),
    ]
