# Generated by Django 5.0 on 2024-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('mobile1', models.CharField(max_length=100, null=True)),
                ('email1', models.EmailField(max_length=100, null=True)),
                ('aadhar1', models.FileField(null=True, upload_to='pics/')),
                ('photo1', models.FileField(null=True, upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReg2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100, null=True)),
                ('c_register_no', models.CharField(max_length=100, null=True)),
                ('c_email', models.CharField(max_length=100, null=True)),
                ('c_mobile', models.CharField(max_length=100, null=True)),
                ('c_address', models.CharField(max_length=100, null=True)),
                ('c_incorporation', models.ImageField(null=True, upload_to='pics/')),
                ('p_card', models.ImageField(null=True, upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirm_password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='regpage',
            name='l_name',
        ),
    ]
