# Generated by Django 5.0 on 2024-02-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_agentreg_customerreg2_user_login_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_login',
            new_name='Registration_user',
        ),
    ]
