# Generated by Django 5.0 on 2024-02-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_login',
        ),
    ]
