# Generated by Django 5.0 on 2024-02-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentreg',
            old_name='fisrt_name',
            new_name='fisrt_name1',
        ),
        migrations.RenameField(
            model_name='agentreg',
            old_name='last_name',
            new_name='last_name3',
        ),
        migrations.RenameField(
            model_name='agentreg',
            old_name='middle_name',
            new_name='middle_name2',
        ),
    ]
