# Generated by Django 5.0 on 2024-02-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_fisrt_name_agentreg_fisrt_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regpage',
            name='l_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
