# Generated by Django 5.0 on 2024-02-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_regpage_l_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegPage',
            new_name='CustomerReg1',
        ),
    ]
