# Generated by Django 5.0 on 2024-02-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_regpage_customerreg1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentreg',
            old_name='fisrt_name1',
            new_name='first_name1',
        ),
    ]
