# Generated by Django 5.0.2 on 2024-02-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_fisrt_name1_agentreg_first_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='images/')),
                ('company_name', models.CharField(max_length=100)),
                ('company_register_no', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_mobile', models.CharField(max_length=15)),
                ('company_address', models.TextField()),
                ('company_incorporation', models.ImageField(upload_to='images/')),
                ('pan_card', models.ImageField(upload_to='images/')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin_registration1',
        ),
        migrations.DeleteModel(
            name='Admin_registration2',
        ),
        migrations.DeleteModel(
            name='Registration_user',
        ),
    ]
