# Generated by Django 5.0.1 on 2024-03-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_registration_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_name', models.CharField(max_length=100, null=True)),
                ('help_email', models.CharField(max_length=100, null=True)),
                ('help_company_name_help', models.CharField(max_length=100, null=True)),
                ('subject_help2', models.CharField(max_length=100, null=True)),
                ('select_department_help', models.CharField(max_length=100, null=True)),
                ('your_massage_help', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
