# Generated by Django 5.0.2 on 2024-03-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_helphire'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentreg',
            name='unique_id',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
