# Generated by Django 5.0.1 on 2024-03-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_agentreg_unique_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReg1',
        ),
        migrations.DeleteModel(
            name='CustomerReg2',
        ),
        migrations.DeleteModel(
            name='PhotoSubmission',
        ),
    ]
