# Generated by Django 5.0.1 on 2024-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_customerreg1_delete_customerreg2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='token',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
