# Generated by Django 5.0.1 on 2024-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_registration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentreg',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentreg',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
