# Generated by Django 5.1.4 on 2025-03-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_agentreg_password_agentreg_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentreg',
            name='password',
        ),
        migrations.RemoveField(
            model_name='agentreg',
            name='username',
        ),
    ]
